// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Final_Project
{
  public partial class QPXReponse
  {
    public class Airport2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("code")]
      public string Code;

      [JsonProperty("city")]
      public string City;

      [JsonProperty("name")]
      public string Name;
    }
  }

  public partial class QPXReponse
  {
    public class City2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("code")]
      public string Code;

      [JsonProperty("name")]
      public string Name;
    }
  }

  public partial class QPXReponse
  {
    public class Aircraft2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("code")]
      public string Code;

      [JsonProperty("name")]
      public string Name;
    }
  }

  public partial class QPXReponse
  {
    public class Tax2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("id")]
      public string Id;

      [JsonProperty("name")]
      public string Name;
    }
  }

  public partial class QPXReponse
  {
    public class Carrier2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("code")]
      public string Code;

      [JsonProperty("name")]
      public string Name;
    }
  }

  public partial class QPXReponse
  {
    public class Data2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("airport")]
      public Airport2[] Airport;

      [JsonProperty("city")]
      public City2[] City;

      [JsonProperty("aircraft")]
      public Aircraft2[] Aircraft;

      [JsonProperty("tax")]
      public Tax2[] Tax;

      [JsonProperty("carrier")]
      public Carrier2[] Carrier;
    }
  }

  public partial class QPXReponse
  {
    public class Flight2
    {

      [JsonProperty("carrier")]
      public string Carrier;

      [JsonProperty("number")]
      public string Number;
    }
  }

  public partial class QPXReponse
  {
    public class Leg2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("id")]
      public string Id;

      [JsonProperty("aircraft")]
      public string Aircraft;

      [JsonProperty("arrivalTime")]
      public string ArrivalTime;

      [JsonProperty("departureTime")]
      public string DepartureTime;

      [JsonProperty("origin")]
      public string Origin;

      [JsonProperty("destination")]
      public string Destination;

      [JsonProperty("destinationTerminal")]
      public string DestinationTerminal;

      [JsonProperty("duration")]
      public int Duration;

      [JsonProperty("mileage")]
      public int Mileage;

      [JsonProperty("meal")]
      public string Meal;

      [JsonProperty("secure")]
      public bool Secure;

      [JsonProperty("onTimePerformance")]
      public int? OnTimePerformance;

      [JsonProperty("originTerminal")]
      public string OriginTerminal;

      [JsonProperty("operatingDisclosure")]
      public string OperatingDisclosure;
    }
  }

  public partial class QPXReponse
  {
    public class Segment2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("duration")]
      public int Duration;

      [JsonProperty("flight")]
      public Flight2 Flight;

      [JsonProperty("id")]
      public string Id;

      [JsonProperty("cabin")]
      public string Cabin;

      [JsonProperty("bookingCode")]
      public string BookingCode;

      [JsonProperty("bookingCodeCount")]
      public int BookingCodeCount;

      [JsonProperty("marriedSegmentGroup")]
      public string MarriedSegmentGroup;

      [JsonProperty("leg")]
      public Leg2[] Leg;

      [JsonProperty("connectionDuration")]
      public int? ConnectionDuration;
    }
  }

  public partial class QPXReponse
  {
    public class Slouse
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("duration")]
      public int Duration;

      [JsonProperty("segment")]
      public Segment2[] Segment;
    }
  }

  public partial class QPXReponse
  {
    public class Fare2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("id")]
      public string Id;

      [JsonProperty("carrier")]
      public string Carrier;

      [JsonProperty("origin")]
      public string Origin;

      [JsonProperty("destination")]
      public string Destination;

      [JsonProperty("basisCode")]
      public string BasisCode;
    }
  }

  public partial class QPXReponse
  {
    public class BagDescriptor2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("commercialName")]
      public string CommercialName;

      [JsonProperty("count")]
      public int Count;

      [JsonProperty("description")]
      public string[] Description;

      [JsonProperty("subcode")]
      public string Subcode;
    }
  }

  public partial class QPXReponse
  {
    public class FreeBaggageOption2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("bagDescriptor")]
      public BagDescriptor2[] BagDescriptor;

      [JsonProperty("pieces")]
      public int Pieces;
    }
  }

  public partial class QPXReponse
  {
    public class SegmentPricing2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("fareId")]
      public string FareId;

      [JsonProperty("segmentId")]
      public string SegmentId;

      [JsonProperty("freeBaggageOption")]
      public FreeBaggageOption2[] FreeBaggageOption;
    }
  }

  public partial class QPXReponse
  {
    public class Passengers2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("adultCount")]
      public int AdultCount;
    }
  }

  public partial class QPXReponse
  {
    public class Tax3
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("id")]
      public string Id;

      [JsonProperty("chargeType")]
      public string ChargeType;

      [JsonProperty("code")]
      public string Code;

      [JsonProperty("country")]
      public string Country;

      [JsonProperty("salePrice")]
      public string SalePrice;
    }
  }

  public partial class QPXReponse
  {
    public class Pricing2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("fare")]
      public Fare2[] Fare;

      [JsonProperty("segmentPricing")]
      public SegmentPricing2[] SegmentPricing;

      [JsonProperty("baseFareTotal")]
      public string BaseFareTotal;

      [JsonProperty("saleFareTotal")]
      public string SaleFareTotal;

      [JsonProperty("saleTaxTotal")]
      public string SaleTaxTotal;

      [JsonProperty("saleTotal")]
      public string SaleTotal;

      [JsonProperty("passengers")]
      public Passengers2 Passengers;

      [JsonProperty("tax")]
      public Tax3[] Tax;

      [JsonProperty("fareCalculation")]
      public string FareCalculation;

      [JsonProperty("latestTicketingTime")]
      public string LatestTicketingTime;

      [JsonProperty("ptc")]
      public string Ptc;
    }
  }

  public partial class QPXReponse
  {
    public class TripOption2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("saleTotal")]
      public string SaleTotal;

      [JsonProperty("id")]
      public string Id;

      [JsonProperty("slice")]
      public Slouse[] Slice;

      [JsonProperty("pricing")]
      public Pricing2[] Pricing;
    }
  }

  public partial class QPXReponse
  {
    public class Trips2
    {

      [JsonProperty("kind")]
      public string Kind;

      [JsonProperty("requestId")]
      public string RequestId;

      [JsonProperty("data")]
      public Data2 Data;

      [JsonProperty("tripOption")]
      public TripOption2[] TripOption;
    }
  }

  public partial class QPXReponse
  {

    [JsonProperty("kind")]
    public string Kind;

    [JsonProperty("trips")]
    public Trips2 Trips;
  }
}